name: CI

on:
  schedule:
    - cron: '10 20 * * *'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.org'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.org'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.14.0, master]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
      - name: Run tests
        run: |
          make test
      - name: Run examples
        run: |
          make run
      - name: Memory leak detect
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y librocksdb-dev valgrind
          make valgrind
